### ISSUE TITLE
misinformation changes

### ISSUE THREAD

**Issue by Tr0llie** [AshAxolotl/Vencord-Plugins#2]
Hi i am one of the people in vencord who actively help in support and in wikis 

first of all 
> Under install guide
please make it clear that we do not help with any third party plugin install and will only help with vencord / vesktop install

we have received some people that use this guide and them needing support and coming to support and asking for help even tho in #faq, it states clearly that we do not provide support for that. you can keep this up but make it clear on what you are saying by
` vencord support only help with vencord install and not plugin / userplugins installs` 

# Note
even tho it is Open souce, people aka normal users don't know how to install custom plugins but they will try and some even got their discord unable to open. so unless u want to help them in ur own server don't bother redirecting them to the official vencord server for custom plugin install.
Sincerely Tr0ll & Vencord contributors

**Comment by AshAxolotl** [comment]
Dont know how I missed that thanks for letting me know. Sorry if I caused any issues

**Comment by Tr0llie** [comment]
> Dont know how I missed that thanks for letting me know. Sorry if I caused any issues

no problem mate i just wanted to let u know to improve ur repo.

**Comment by Tr0llie** [comment]
also just for ref ur uh ur guide needs some improvment as it requires some other step to get it fully working for some other plugins

**Comment by AshAxolotl** [comment]
tried to improve the guide hope its a bit better now. If there is anything i should still change let me know
